#!/usr/bin/env bash

pdffile=${1}

pid=$$
tmpfile=${pdffile%.pdf}.${pid}.pdf
pngfile=${pdffile%.pdf}.png
# pngfile2=${pdffile%.pdf}_small.png

pdfcrop --margins 1 ${pdffile} ${tmpfile}
magick -density 300 ${tmpfile} ${pngfile}
# magick -density 150 ${tmpfile} ${pngfile2}
rm ${tmpfile}

exit
